
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST") { "127.0.0.1" } %>
  username: <%= ENV.fetch("DB_USER") %>
  password: <%= ENV.fetch("DB_PASS") %>

development:
  <<: *default
  database: snackswap_dev

test:
  <<: *default
  database: snackswap_test

production:
  primary: &primary_production
    <<: *default
    database: api_production
    username: api
    password: <%= ENV["API_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: api_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: api_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: api_production_cable
    migrations_paths: db/cable_migrate
