source 'https://rubygems.org'

gem 'rails', '~> 8.0.3'
gem 'mysql2', '~> 0.5'
gem 'puma', '>= 5.0'
gem 'tzinfo-data', platforms: %i[ windows jruby ]

gem 'bcrypt', '~> 3.1', '>= 3.1.20'
gem 'dotenv-rails', '~> 3.1', '>= 3.1.8'
gem 'graphql', '~> 2.5', '>= 2.5.14'
gem 'interactor-rails', '~> 2.3'
gem 'jwt', '~> 3.1', '>= 3.1.2'
gem 'pundit', '~> 2.5', '>= 2.5.2'
gem 'rack-cors', '~> 3.0'

gem 'solid_cache'
gem 'solid_queue'
gem 'solid_cable'

gem 'bootsnap', require: false
gem 'kamal', require: false

gem 'thruster', require: false

group :development, :test do
  gem 'awesome_print', '~> 1.9', '>= 1.9.2'
  gem 'debug', platforms: %i[ mri windows ], require: 'debug/prelude'
  gem 'brakeman', require: false
  gem 'factory_bot_rails', '~> 6.5', '>= 6.5.1'
  gem 'faker', '~> 3.5', '>= 3.5.2'
  gem 'fuubar', '~> 2.5', '>= 2.5.1'
  gem 'graphiql-rails', '~> 1.10', '>= 1.10.5'
  gem 'pry', '~> 0.15.2'
  gem 'rubocop-rails-omakase', require: false
end

group :test do
  gem 'rspec-graphql_matchers'
  gem 'rspec-rails', '~> 8.0'
  gem 'shoulda-matchers', '~> 6.5'
  gem 'simplecov', '~> 0.22.0'
end
